apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ..\docker-compose.prod.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: customer-self-service-frontend
  name: customer-self-service-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: customer-self-service-frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ..\docker-compose.prod.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: customer-self-service-frontend
    spec:
      containers:
        - image: abdullahalmaz/customer-self-service-frontend
          name: customer-self-service-frontend
          ports:
            - containerPort: 80
          resources: {}
          env:
            - name: REACT_APP_CUSTOMER_SELF_SERVICE_BACKEND
              value: http://20.76.107.80:8080
            - name: REACT_APP_CUSTOMER_MANAGEMENT_BACKEND
              value: http://20.31.93.193:8100
      restartPolicy: Always
status: {}
