apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ..\docker-compose.prod.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: customer-core
  name: customer-core
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: customer-core
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ..\docker-compose.prod.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: customer-core
    spec:
      containers:
        - env:
            - name: SPRING_BOOT_ADMIN_CLIENT_URL
              value: http://20.93.228.7:9000
          image: backis9/customer-core
          name: customer-core
          ports:
            - containerPort: 8110
          resources: {}
      restartPolicy: Always
status: {}
