apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ..\docker-compose.prod.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: customer-core
  name: customer-core
spec:
  type: LoadBalancer
  ports:
    - name: "8110"
      port: 8110
      targetPort: 8110
      protocol: TCP
  selector:
    io.kompose.service: customer-core
