apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ..\docker-compose.prod.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: spring-boot-admin
  name: spring-boot-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spring-boot-admin
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ..\docker-compose.prod.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: spring-boot-admin
    spec:
      containers:
        - image: backis9/spring-boot-admin
          name: spring-boot-admin
          ports:
            - containerPort: 9000
          resources: {}
      restartPolicy: Always
status: {}
